### ISSUE TITLE
Script options with px:type="xs:boolean"

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline#471]
Script options with a px:type of xs:boolean could be given values `true()` and `false()` instead of `"true"` and `"false"`. I don't even know whether this is supported by XProc. Are `true()` and `false()` valid xs:untypedAtomic? See http://www.w3.org/TR/xproc/#p.option.

Related: https://github.com/daisy/pipeline-framework/pull/84

**Comment by josteinaj** [comment]
I'm using `select="'true'"` and `select="'false'"` since I think I had an issue with using booleans sometime in the past. But I did some tests now, both using XPath 1.0 and 2.0 and it doesn't seem to make a difference if you substitute it with `select="true()"` and `select="false()"`.

From http://www.w3.org/TR/xpath-datamodel/ :
> When xs:untypedAtomic is specified as the type, no validation takes place.

and
>  No predefined types are derived from xs:untypedAtomic.

So I would assume all values are valid xs:untypedAtomic ?

**Comment by bertfrees** [comment]
Do you mean that in your test, the XPath expression `if ($var) then 'foo' else 'bar'`, where `$var` is an XProc variable with value `false()`, evaluates to `'foo'`?

**Comment by josteinaj** [comment]
Ah, you're right. That doesn't work. I tried `$var = 'true'` and `$var = true()` which works, but it works because it performs string comparison.

In your case `$var` is evaluated as a string but not compared to anything, and all non-empty strings in XPath evaluates to true.

You can still use `true()` and `false()` in the select expression but you always need to compare it as a string in your scripts, so using the string version makes it more clear for the script author that they need to use string comparison.

I think this will be fixed in XProc 2.0.

**Comment by bertfrees** [comment]
I thought that xs:untypedAtomic maybe meant that the values are casted automatically to the right type. But it seems it's more like a string. OK so I guess the conclusion is that this feature is impossible to do now because of the way XProc currently works.
