### ISSUE TITLE
GUI does not start and no clues given to the user at all

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline#521]
This was reported by George. He is using Windows.

One issue is that the GUI doesn't start. A more important issue is that the user doesn't get any information.

**Comment by bertfrees** [comment]
While trying to reproduce George's issue on Sean's machines, he got across several other issues. He has made an overview of what happens in various cases:

https://docs.google.com/document/d/1CTb_2BZFMoNzkZFPzBBkwjunnkxBr0qzDRivyL-U26M

So this is what we need to do:

- [ ] Fix the regedit prompt which is not so user-friendly and doesn’t seem to work. We need to find out why the regedit prompt does not appear when the VBS or BAT script is run from the command line, and whether that has something to do with the GUI working in this case.
- [ ] Fix the VBS script which has no command line output. This is not really a problem because the VBS script is not meant to be run from command line, but it would still be good if it can be fixed.
- [ ] Fix the empty log file when the BAT script is run from command line. There is a non-empty log file in all the other cases (when JAVA_HOME set) so I don't get why in the BAT case it would be different. The log file is created by the Pipeline Java application itself.
- [ ] Fix the missing log file in George's case. The solution is probably to make the BAT script write to some log file. (But the problem could in theory also be something else.)
- [ ] Possibly fix another unidentified issue George is having.
- [ ] Document everything that the installer does.

Sean had another issue with his JAVA_HOME variable being cleared at some point, but we don't know if this is related to something the Pipeline does.

**Comment by mccallum-sgd** [comment]
>Fix the missing log file in George's case.

We didn't think to look in George's `%appdata%` folder for the logs, so they could very well be there. We plan to contact George about this when he gets back from vacation.

>Sean had another issue with his JAVA_HOME variable being cleared at some point, but we don't know if this is related to something the Pipeline does.

I haven't had this problem since it first happened in initial testing, so I think it's safe to assume this was due to a mistake I made (e.g. not saving changes to environment variables before re-running). I will definitely be keeping an eye on this though.

**Comment by bertfrees** [comment]
@mccallum-sgd I'm working on branch [`issue-521`](https://github.com/daisy/pipeline/compare/master...issue-521). I've made the batch file write to a log file. Next thing is to find out why the regedit code does not work if the Pipeline is launched from the start menu. Just looking at the log files should give us a clue. If needed we can add move messages.

**Comment by mccallum-sgd** [comment]
Tested it again, all in my summary: https://goo.gl/GyZx6T

**Comment by bertfrees** [comment]
@mccallum-sgd So I checked off some things in the list because it seems they are not reproduced anymore. Most important thing now I think is to find out why the code for finding Java via the registry doesn't work.

Also I think some prompt telling the user that the Pipeline failed to start, and pointing him to the log file, would be nice. I presume this could be implemented in the VBS script.

**Comment by mccallum-sgd** [comment]
Okay, sounds good. It seems a message box isn't difficult to implement in vbs, so I'll throw that together first.

**Comment by mccallum-sgd** [comment]
@bertfrees Added the dialog here: 2710343. I tested it by just dragging it into my install folder, but I couldn't figure out how to add it to the build with Maven.

**Comment by bertfrees** [comment]
Good job! What I had in mind though was to show the dialog only when you run Pipeline from the pipeline2-{gui,webservice}.vbs script and fails to start. Not when you run the BAT script directly, I think it is more appropriate in that case to just print to STDOUT. But it's open for discussion. Another thing is that the dialog is shown regardless of whether there was an error.

Pointing users to Github to report an issue is a  good idea, but I would not point them to https://github.com/daisy/pipeline/issues/521, I think that could be confusing. I would point them to https://github.com/daisy/pipeline/issues/new, or even better to a page on our website that explains how to file an issue.

**Comment by mccallum-sgd** [comment]
Thanks Bert, it turned out to be a bit more complicated than I thought! 

Yeah I wasn't quite sure how to set it up so that it only runs when the gui fails (or I suppose the web service too) so I just did the next best thing for now. Is there even a way to do this from the vbs script? I agree that it should be command line output when you run the pipeline server, but from my testing I don't think that's happening right now, so that's another thing to fix. 

I didn't realize you can link to a new issue, and yes an issue guide page would be perfect. I think we've talked about that sort of thing before.

**Comment by bertfrees** [comment]
> I agree that it should be command line output when you run the pipeline server, but from my testing I don't think that's happening right now, so that's another thing to fix.

Yes, I realized that too. I already fixed that, but forgot to push it. See f23174aa709dd7b2ba5c36706bc875ade02550ec

>> show the dialog only when you run Pipeline from the pipeline2-{gui,webservice}.vbs script > and fails to start
>
> Is there even a way to do this from the vbs script?

The BAT script would have to return a value "0" or "1", the VBS script would test this value and only call the msgbox-guinostart.vbs script if the value is "1".

https://ss64.com/nt/exit.html

**Comment by mccallum-sgd** [comment]
Ahh okay that's perfect! But we could still move the message box script to pipeline-gui.vbs as a subroutine if you think that's appropriate. I don't think it would be too unclear what's happening and it would cut down on one extra file. Whatever the case I can finish that this afternoon.

**Comment by bertfrees** [comment]
Changing to a subroutine sounds good.

**Comment by mccallum-sgd** [comment]
Added the dialog in d03c602

I set it up a little differently than before, so if we want to preserve the "logs weren't created, report issue?" message then I would need to add a check within the vbs launchers for the logs being created (previously handled in `pipeline2.bat`) . I tried to implement this yesterday, but I was getting a concerning permissions error for the process that creates a [`FileSystemObject`](https://msdn.microsoft.com/en-us/library/z9ty6h50(v=vs.84).aspx).

If we still want to cover this then I can do that, but there really shouldn't be any reason for the logs to not be created now. I added an `if not exist, ... mkdir` line to the beginning of `pipeline2.bat` in that same commit.

This took quite a while, definitely longer than I expected, but I did learn _a lot_ about how the pipeline is run, vbscript, and batch.

Anyway, I'll focus on getting the other issues tested now.

Checked off:  
> Fix the VBS script which has no command line output

**Comment by mccallum-sgd** [comment]
Just added the check for if the logs were created, works great and I didn't get the error I got last time.
___
> Fix the regedit prompt which is not so user-friendly and doesn’t seem to work

I think a better solution than starting regedit might be to use [Reg Query](https://technet.microsoft.com/en-us/library/cc742028(v=ws.11).aspx). 
For example, this: 
[`start /w regedit /e __reg1.txt "HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment"`](https://github.com/daisy/pipeline/blob/master/assembly/src/main/resources/bin/pipeline2.bat#L97)
Might become this:
`reg query HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment > __reg1.txt`

I did a bit of testing and this finds the correct key, with no regedit prompt, but it doesn't fully work. I'm thinking it's just because it's in a different format than what's returned by starting regedit (I'm unable to compare because our current solution doesn't return anything for me), so it how it extracts the data from the output would have to be revised a bit.

**Comment by bertfrees** [comment]
Good progress!

Just a few comments:
- http://daisy.github.io/pipeline/Contribute/#issue-tracker

**Comment by bertfrees** [comment]
Good progress!

A few comments:

- Consider moving the common code between pipeline2-gui.vbs and pipeline2-webservice.vbs into a shared file.
- Can we change the "reportIssue" link to http://daisy.github.io/pipeline/Contribute/#issue-tracker? (I'll improve that page later.)
- It seems like you moved `pause` to underneath `:END_NO_PAUSE`. That does not make sense. Or does it?
- You check in VBS for exit code "4", but where in the BAT are you setting it to "4"?
- You are not using the `/b` argument of `exit`. Is that done for a specific reason? From reading the manual page of exit the argument seemed kinda useful.
- Some thoughts about coding style: When doing a lot of white space changes (notably parts of the "Code organisation" commits) I think it's better to do them in a separate commit, makes the diffs that matter more apparent. Also be careful with mixed spaces and tabs. Also, merge commits are to be avoided if not really needed, like the one at d03c602. (You don't have to go and change things now, I can clean it up when I merge the branch.)

**Comment by mccallum-sgd** [comment]
> Consider moving the common code into a shared file.

Yes I was thinking this, it's very redundant. I can do that.

> Can we change the "reportIssue" link?

Sure can, looks like a good place to send them.

> It seems like you moved pause to underneath :END_NO_PAUSE

I did this accidentally in previous commits, but from what I can see it's removed in the most recent commit. The only reason I did this was to see the BAT's output during testing.

> where in the BAT are you setting it to "4"?

I can see how this would be confusing. This is actually the code I pass in from the `viewLogs()` subroutine if the logs directory doesn't exist. 

I'll add a comment for this and probably change the `errorPrompt`'s local variable name to something like "errorCode" to be more clear.

> You are not using the /b argument of exit
`exit /b` exits the current call, whether that's a subroutine within the batch file or the batch file itself. 

When I `call:fail`, it never exits that subroutine's control because it just goes straight to `:FAILURE`, instead of returning control with a `goto :EOF`. So if I were to use `exit /b` in this case, it would return control to where :fail was called initially, which is definitely not what we want. To fix this, I removed the /b argument, and it worked.
 
I used a separate :fail label because I wanted to be able to pass in the :warn message as well, making the call more concise (as opposed to call:warn and goto FAILURE). I know it's unconventional and pretty unclear; it took me a while to even realize what was happening, but it works. 
 
If you want me to change it to just the :FAILURE label, I can do that. I suppose I just liked the notion of `call:fail` more -- less messy but I can see now it makes what happens after very confusing.

> Some thoughts about coding style
I know my commits were very messy, I was having quite a bit of trouble with Git (corrupt objects, lots of accidental merges & conflicts, etc.), still a lot to learn.

> I think it's better to do them in a separate commit
That's basically what I had in mind, but I did end up mixing in what I felt was "code organization" changes. I will keep these separate in the future.

> be careful with mixed spaces and tabs
I wasn't aware there were tabs in there, I definitely checked for that but I guess I must have missed some. 

> merge commits are to be avoided if not really needed
Yes, I wasn't aware at the time that there was a way around this. If it's all the same I would like to attempt this, I really want to get past these problems and learn more about Git. I know it will take a lot longer if I do it but I also know it will be worth it in the end.

Let me know what you think and I can make the appropriate changes.

**Comment by mccallum-sgd** [comment]
Made the changes in 61677f01304013bb25ed73cbdaa4a0c96ebfe533

**Comment by bertfrees** [comment]
>> It seems like you moved pause to underneath :END_NO_PAUSE
>
> [...] but from what I can see it's removed in the most recent commit

Ah, you're right, I see it now.

> I was having quite a bit of trouble with Git

Don't worry about it, it can take a while to properly learn Git. Leave it up to me this time, I've become quite good at fixing up commits over the years. And let me know if you have any questions about Git!

**Comment by mccallum-sgd** [comment]
Alright, thanks bert. I'll be sure to ask if I have any questions.

**Comment by mccallum-sgd** [comment]
Added troubleshooting page in 8b63bf3d4df663ad1e3558c67441165e386a45bc. Checked off on list. Currently it only provides instructions for Windows users but this is mainly what we need to cover for now.

**Comment by mccallum-sgd** [comment]
@bertfrees 
I categorized the possible startup issues in pipeline2.bat by **unknown**: not handled, **user-fixable**: section for possible fix in troubleshooting, and **fatal**: requires the user to create a new issue. I then amended `errorPrompt.vbs` to point open the logs automatically in the background and point them in the right direction (new issue for **unknown** and **fatal**, troubleshooting for **user-fixable**).

I also added the issue template and moved the issue tracker section on our website to a new page in the user documentation (added a section there for directions to provide error logs via a GIST in new issues).

**Comment by josteinaj** [comment]
We just experienced what might be the same issue when installing on @usama49's Windows 10 computer. I noticed that the VBS referenced `pipeline2.bat`, but was run from `C:\Program Files (x86)\DAISY Pipeline 2` instead of `C:\Program Files (x86)\DAISY Pipeline 2\daisy-pipeline\bin`. After adding `\daisy-pipeline\bin` to the "Start in:" path it worked. It takes several seconds to start though, so it would be useful to have a splash screen.

![2017_11_21_17_35_56_daisy_pipeline_2](https://user-images.githubusercontent.com/295481/33084866-508cd6ce-cee3-11e7-8831-e2789b31bf44.png)

**Comment by bertfrees** [comment]
I've create a PR for the website changes: https://github.com/daisy/pipeline/pull/526.

**Comment by bertfrees** [comment]
I have done some more work regarding this issue:

- implemented a Splash screen
- time out when the GUI could not be started
- further fixed/improved logging of the pipeline2.bat script
- fixed a bug in the VBS scripts (they relied on the installer adding the "daisy-pipeline/bin" directory to the %PATH%)

**Comment by bertfrees** [comment]
Fixed in 90a4482c4db453cf672ee1cc6f95a570cc8c5bff, https://github.com/daisy/pipeline-assembly/commit/30a14d1147783bbb88f7688e023052d6a0d865c0 and https://github.com/daisy/pipeline-gui/commit/5d8290273083f5d94900fc728e4358db513cdec3

**Comment by bertfrees** [comment]
I am closing this issue now. The action items in https://github.com/daisy/pipeline/issues/521#issuecomment-328958999 that are not done yet can be moved to new issues if we think they are important enough.
