### ISSUE TITLE
EPUB 3 to DAISY 2.02 giving errors

### ISSUE THREAD

**Issue by flittle8** [daisy/pipeline#529]
Hi- we have tried to convert various EPUB 3 books to DAISY 2.02 with Pipeline 2, but with no success yet. Attached is one of the recent errors. It would be great to know how we can ensure that the EPUB 3 content we receive will convert successfully. Thanks for looking into this.
![epub3-daisy202-error](https://user-images.githubusercontent.com/23460746/35755642-ec2f4ae0-081c-11e8-9c89-cccd8b5502ee.png)

**Comment by josteinaj** [comment]
Hi @flittle8.

In the messages panel it looks like the dc:identifier is missing. Maybe the dc:identifier metadata is missing from the package document.

There are however unfortunately at least one known issue with the script, so that the resulting fileset becomes invalid: https://github.com/daisy/pipeline-scripts/issues/92

We also need this script working at NLB soon, but haven't had time to work on fixing / improving it.

**Comment by bertfrees** [comment]
@josteinaj In commit https://github.com/daisy/pipeline-scripts/commit/dd5c999d3860c7085b632d80436ccedcc0c5960c you removed the DAISY 2.02 and EPUB validation steps. Why was it not needed anymore? Why did you add the dc:identifier test at the end? It would be more user-friendly to have a validation of the input and abort immediately if the EPUB has no dc:identifier.

Related: https://github.com/daisy/pipeline-scripts/issues/112

**Comment by flittle8** [comment]
@josteinaj Thanks for the reply. The strange thing is that the dc:identifier is there, and it's a valid EPUB 3 (passes EPUB-Checker with 0 errors). Good to know that the script is being worked on - thanks!

**Comment by josteinaj** [comment]
@bertfrees dropping validation reduces the amount of dependencies. We could always re-add optional validation if you think it makes sense. In a production workflow it's likely that the input and output is validated as part of a bigger system/workflow.

Checking that the identifier is present is useful because the identifier is used as part of the pathname, and we want a predictable output path.

@flittle8 We'll make sure to have an extra look at the identifier issue you're having when we get around to improving the script. Thanks for reporting it!

**Comment by bertfrees** [comment]
Yes I think I would re-add input validation. Validation makes sense for all scripts that make some assumptions on the input. But of course it should be optional because as you say the input is often validated already. Full validation might not always be necessary, but at the very least the script should show error messages about the input while processing it. Errors about the output are confusing for the user.

@flittle8 Romain told me you already sent us a sample document. Thanks for that.

**Comment by bertfrees** [comment]
The problem is that there are 2 `dc:identifier` elements in the input OPF, which are both copied to the output NCC. This appears to be valid in EPUB but I don't know if it's valid in DAISY. For now I'll just use the first identifier for the output directory name.

**Comment by bertfrees** [comment]
PR: https://github.com/daisy/pipeline-scripts/pull/142

**Comment by flittle8** [comment]
@bertfrees I just tried running this script again using a valid EPUB 3 with no errors (using EPUB-Checker) and I still received the 2 errors in the attached screenshot. (And there is a dc:identifier in the content.opf) I haven't had any luck with this script yet on valid EPUB 3 files, so not sure what's up... Thanks!
![epub3-daisy202](https://user-images.githubusercontent.com/23460746/45898329-9c20a600-bdd1-11e8-8dbf-a240f13fef53.png)

**Comment by bertfrees** [comment]
Hi @flittle8. Which version are you tried? This fix will be in version 1.11.1 which is not released yet (but will be soon).

**Comment by flittle8** [comment]
Ah perfect, thanks! I’m using the latest release

**Comment by flittle8** [comment]
@bertfrees So, I downloaded the new Pipeline 1.11.1 and tried out the EPUB 3 to DAISY 2.02 script again (using the same valid EPUB 3 file) and, good news - a folder was actually output with no errors, but bad news - the output file doesn't seem to be a valid DAISY 202. In case this is useful for you:
    - I can't open the DAISY with ReadHear Pro for Mac or Emerson
    - The daisy does not validate using the Daisy 2.02 DTB Light Validator (221 issues reported)
    - I’m using a well-structured and valid EPUB 3 (epub-checker)
I can provide more info if needed just let me know!

**Comment by flittle8** [comment]
Attached is the log file
[log.txt](https://github.com/daisy/pipeline/files/2438218/log.txt)

I also received a validation message:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><d:validation-status xmlns:d="http://www.daisy.org/ns/pipeline/data" result="ok"/>`

**Comment by bertfrees** [comment]
Are you using the same file that you sent us before?

**Comment by flittle8** [comment]
@bertfrees yes, I tried it on a few valid EPUB 3's including the 2 I had sent Romain back in Feb. When I run them through, they all output an invalid daisy that I'm not able to open in our software

**Comment by bertfrees** [comment]
I have created a new issue: https://github.com/daisy/pipeline-scripts/issues/150

**Comment by bertfrees** [comment]
@flittle8 It seems the epub3-to-daisy202 is really not production ready yet as it contains many known bugs. The script hasn't gotten much attention because we don't get much requests for it. I think we should finally put some work in it, or otherwise remove it from the list. I will let you know when we have an idea of the timeline.

**Comment by flittle8** [comment]
@bertfrees Thanks, I did suspect that might be the case :) It would be super fantastic if this script worked as most publisher content we receive is in EPUB format & our remediation work is starting to happen directly within EPUB. So being able to convert from a valid accessible EPUB 3 to DAISY 202 would be extremely useful and time-saving as most of our patrons still request DAISY... 
If NNELS can help in any way to further push this forward, do let me know.
