### ISSUE TITLE
JAVA_HOME not set after installing

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#531]
### Expected Behavior

1. Click "DAISY Pipeline 2" from the start menu
2. The desktop application should start

### Actual Behavior

1. Click "DAISY Pipeline 2" from the start menu
2. Confirm that you want to allow changes to the registry
3. Confirm that you want to allow changes to the registry (again)
4. An error appears with "DAISY Pipeline 2 was unable to start. We may have a solution for this error. Visit troubleshooting?"
5. Clicking "Yes" does nothing.

### Steps to Reproduce

1. From https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ download MSEdge on Win10 (x64) Preview (17.17127) for Virtualbox
2. Start the VM and download v1.11.0 from daisy.github.io/pipeline
3. After installing (which includes installing Java), try starting the desktop application

### Details

When trying to run `pipeline2.bat gui` from the terminal, this is the output:

```
C:\Program Files (x86)\DAISY Pipeline 2\daisy-pipeline\bin>pipeline2.bat gui
pipeline2.bat: 2018-04-27  8:02:13
pipeline2.bat: JAVA_HOME not set; results may vary
pipeline2.bat: Unable to retrieve JAVA_HOME
pipeline2.bat: Exiting with value 2
```
`java` is on the path after installation, but JAVA_HOME is not set.

Setting JAVA_HOME manually fixed the issue.

### Environment

* Operating system: Windows 10 64-bit
* DAISY Pipeline 2 version: 1.11.0
* Interface: GUI

**Comment by bertfrees** [comment]
> Confirm that you want to allow changes to the registry

This is a problem because

1. You shouldn't have to give permission to make changes to the registry because we aren't making changes.
2. You should definitely not have to give permission twice.
3. The reason for all this is that we inspect the registry to get JAVA_HOME, but clearly it is not even working.

This problem is also described in https://github.com/daisy/pipeline/issues/521.

**Comment by mccallum-sgd** [comment]
> Clicking "Yes" does nothing.

Looks like the URL is incorrect: https://github.com/daisy/pipeline/blob/master/assembly/src/main/nsis/errorPrompt.vbs#L74
It should be: https://daisy.github.io/pipeline/Get-Help/Troubleshooting/

Maybe we could somehow validate the URL first, and if it's not correct just direct them to the homepage. That way at least something happens if the URL is incorrect in the future. And we also might want to display another error message along the lines of "Error: Troubleshooting URL is invalid", and direct them to opening a new issue.

Of course a better solution would be to get correct the URL automatically from the website module somehow, any ideas @bertfrees ?

**Comment by bertfrees** [comment]
@mccallum-sgd Thanks for figuring out the problem. I'm just going to fix the link and maybe [add a 404 page to the website](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site).

We should have a look at #521 again. You had this idea of using reg query.

**Comment by mccallum-sgd** [comment]
Alright sounds good, and yes I did -- it seemed to work without a UAC prompt when I created a simple test script (see [issuecomment-333408840])https://github.com/daisy/pipeline/issues/521#issuecomment-333408840)). Should we create a new issue for this?

**Comment by bertfrees** [comment]
Yes

**Comment by bertfrees** [comment]
[This page](https://ss64.com/nt/reg.html) confirms that reg.exe, unlike regedit, does not always require elevation.

**Comment by bertfrees** [comment]
[This page](https://ss64.com/nt/syntax-elevate.html) provides a trick to do it with regedit.

**Comment by mccallum-sgd** [comment]
I ended up just using `reg query` (see https://github.com/daisy/pipeline-assembly/issues/154#issuecomment-397110535).

**Comment by bertfrees** [comment]
PR: https://github.com/daisy/pipeline-assembly/pull/158
