### ISSUE TITLE
Daisy pipeline 2 command line dp2.exe doesn't work

### ISSUE THREAD

**Issue by Iamsrinath5** [daisy/pipeline#549]
In our application we wrote logic for different file conversions and therefore using Daisy scripts.
I am trying to run dp2.exe by passing the required parameters. But it doesn't actually work .

Initially i get 'launching the pipeline webservice...' message and after that ends with message
"Error bringing the pipeline2 up I have been waiting 60 seconds for the WS to come up but it did not "

### Environment
*  Windows 10 64-bit 
* DAISY Pipeline 2 
*  Interface : Command Line

**Comment by bertfrees** [comment]
Experience shows that starting the web server can take a while. It is possible that if you try running the CLI a second time it does work.

If this doesn't work, would it be possible to send us the log files? See http://daisy.github.io/pipeline/Get-Help/Issue-Tracker.html for where to find these.

It could also a good idea to launch the web server manually because in this case there will be more possibly useful logging. You should be able to find a shortcut for running the web server in the start menu.

It is a known issue is that the web server does not work with the version of Java that is automatically downloaded by the DAISY Pipeline installer. Java 8 is know to work fine. These are the steps you can take to make Pipeline run with Java 8 (but it will only work if you haven't got a Java version >= 11 installed globally):
- Uninstall and reinstall DAISY Pipeline 2 but choose "No" when the installer suggests to download and install Java automatically. Alternatively, you can go into the `C:\Program Files (x86)\DAISY Pipeline 2\daisy-pipeline` folder and rename the `jre` folder to something else.
- Install Java 8
- Set your `JAVA_HOME` environment variable to the location of the Java 8 installation. For example, on my machine this is "C:\Program Files\Java\jre1.8.0_201". If you are using PowerShell you can change an environment variable temporarily with `$env:JAVA_HOME = "C:\Program Files\Java\jre1.8.0_201"`. But you can also go to the control panel and change it there.
- Try running `dp2` again. (Note that if you changed the environment variable temporarily as described above you need to run it in the same PowerShell window.)

Hope this helps.

**Comment by Iamsrinath5** [comment]
Hi Bert,
I am using java 11 (jdk11.0.5)
I have also tried increasing the timeout from 60 to 600 seconds in
config.yml file
But still no progress...
I will share the log files for the same.

Would you please inform me what are the inputs that are required to run the
dp2.exe

**Comment by bertfrees** [comment]
> Would you please inform me what are the inputs that are required to run the dp2.exe

What do you mean?

**Comment by Iamsrinath5** [comment]
Hi Bert,
I am new to Daisy pipeline 2 and I need help with running dp2.exe in cmd.
What is the correct way to do that?

What are the input parameters that are required to run dp2.exe?

Even help command is not working for me.

Please refer to the attached screenshot.

**Comment by bertfrees** [comment]
I'm sorry, there is no screenshot. If you reply to an email from Github with an attachment, the attachment is lost.

But anyway, if you say you are getting a "Error bringing the pipeline2 up" error, I think it's no use explaining how to use the CLI. `dp2 help` should be all you need, so we first have to get that working.

You need to try with Java 8 like I explained above. Just follow the steps, then report back. If it is still not working, please provide the log files as explained in http://daisy.github.io/pipeline/Get-Help/Issue-Tracker.html.

Thanks,
Bert

**Comment by Iamsrinath5** [comment]
Hi Bert,
Appreciate your help and support.
dp2 help is working fine. Could you please guide me how to run commands for
file conversions
I have referred readme.txt file but it's not much helpful for me.

**Comment by bertfrees** [comment]
Ah, OK, good.

`dp2 help` should be self-explanatory. There is also documentation about the CLI and the scripts in our [user guide](http://daisy.github.io/pipeline/Get-Help/User-Guide/), but all this documentation is also available from the command line itself. Just start with `dp2 help`, and it'll explain you how you can get additional information about the scripts and the script options.

A typical `dp2` command is the following:

    dp2 dtbook-to-pef --source hauy_valid.xml -o /Users/bert/Desktop/out --stylesheet braille.css --include-brf true

To get available options of a script:

    dp2 help dtbook-to-pef

and to get a detailed description about an option:

    dp2 help dtbook-to-pef stylesheet

**Comment by Iamsrinath5** [comment]
Hi Bert,
I tried running  script command html-to-epub3
but I get the the error

--i-metadata is not a valid flag for html-to-epub3

With dtbook-to -epub3, i get the error as
--i-source is not a valid flag for dtbook-to-epub3

When I tried removing --i-metadata and
--i-source and run respective commands
I face the issue with
--metadata is mandatory for command html-to-epub3 and similar error with
the other command

The command I ran in my machine was
dp2 dtbook-to-epub3
--i-source
C:\users\username\Desktop\filesample.xml
--output C:\users\username\Desktop\
Please correct me if anything is wrong.

**Comment by bertfrees** [comment]
Can I ask where you found the command that you ran? It is an old format. The correct command is:

    dp2 dtbook-to-epub3 --source C:\users\username\Desktop\filesample.xml --output C:\users\username\Desktop\

You just need to do what `dp2 help` tells you to do.

**Comment by Iamsrinath5** [comment]
Hi Bert,
Thanks for correcting me!
I tried running  the below
 command but still i get  'unexpected error'

C:\Program Files (x86)\DAISY Pipeline 2\daisy-pipeline\cli>dp2 dtbook-to-epub3 --source C:\Users\Srinath\Desktop\filesample.xml --output C:\Users\Srinath\Desktop\
Checking java
Error:
        unexpected error

Please refer to the screenshot and log files for the same
https://user-images.githubusercontent.com/58396662/70350769-64decd80-188d-11ea-9a45-50d7db88aefb.PNG

[daisy-pipeline-java.log](https://github.com/daisy/pipeline/files/3933728/daisy-pipeline-java.log)
[daisy-pipeline-webservice.log](https://github.com/daisy/pipeline/files/3933729/daisy-pipeline-webservice.log)
[derby.log](https://github.com/daisy/pipeline/files/3933730/derby.log)

**Comment by bertfrees** [comment]
I apologize, my example contained an absolute file path, but unfortunately this is currently not supported on Windows. It is a bug. You either have to use a relative path, or I need to release a new version of the CLI. Let me know. I can do it on Monday.

**Comment by Iamsrinath5** [comment]
Hi Bert, 
I tried running the command using relative path and it worked for me. However,
the newer version of CLI may provide complete solution for this. Please release the same.

**Comment by bertfrees** [comment]
I have published a new version here: https://github.com/daisy/pipeline-cli-go/releases/tag/v2.1.3

**Comment by Iamsrinath5** [comment]
Thanks a lot Bert!! It worked absolutely fine.
However , I am confused with one more thing.
Does accessing CLI (newer or earlier version) requires administrator
privileges? Or any user has access to it?
Since when I run the CLI as a normal user it won't start and get 60 seconds
timeout error but works fine when I run it with administrator account.

**Comment by bertfrees** [comment]
Not that I am aware of. But to be honest I have no idea, I don't know that much about Windows. Maybe it depends on how you installed DAISY Pipeline?

**Comment by Iamsrinath5** [comment]
Thanks for the suggestion Bert.
I am trying to convert a dtbook format to braille , where i am getting job failed exception , Please guide me in running the command correctly.
Below is the issue: 
java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(translator:liblouis)(formatter:dotify)(locale:und) (Please see detailed log for more info.)
The command i run was
dp2 dtbook-to-pef --source C:\input\test.xml --include-preview true --include-brf true --output C:\input\out

**Comment by bertfrees** [comment]
This is probably because the script expects the input document to have a `xml:lang` attribute on the root element.

**Comment by Iamsrinath5** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
<title>
Test 
</title>
</head>
<body>
<h1>This is heading</h1>
<p>This is paragraph one</p>
<p>This is paragraph two</p>
</body>
</html>

**Comment by Iamsrinath5** [comment]
Thanks!!!
I am facing same issue with html-to-pef 
Please find the attached sample code snippet i ran.
[test.txt](https://github.com/daisy/pipeline/files/3961866/test.txt)

**Comment by bertfrees** [comment]
Again, the input should have a `xml:lang` attribute.

**Comment by Iamsrinath5** [comment]
Thanks Bert,
I was running the scripts  daisy3-to-daisy202 with the below command
dp2 daisy3-to-daisy202 --source C:\input\daisy3\output-dir\greatpainters.xml --output C:\input\daisy3\out
 and getting the error 'The input DTB type ('') is not supported'
wouldyou please help me with this?

**Comment by bertfrees** [comment]
The input of this script should be a DAISY 3 package file (.OPF extension).

**Comment by Iamsrinath5** [comment]
Tried that!
But still similar issue...
C:\Program Files (x86)\DAISY Pipeline 2\daisy-pipeline\cli>dp2 daisy3-to-daisy202 --source C:\input\daisy3\output-dir\book.opf --output C:\input\daisy3\out
Job 9f37e30d-2e2a-4a08-909e-6f166ca2af74 sent to the server
                                                                         0.0%
                           The input DTB type ('textNCX') is not supported.
                        (Please see detailed log for more info.)

**Comment by Iamsrinath5** [comment]
tried with different input as well
dp2 daisy3-to-daisy202 --source C:\Users\Srinath\Downloads\are-you-ready-z3986\Are_you_ready_z3986\speechgen.opf --output C:\input\daisy3\out
Job 696b383d-8c71-4fb0-9bc5-21821e24b02c sent to the server
                                                                         0.0%
                           The input DTB type ('audioFullText') is not supported.
                        (Please see detailed log for more info.)

**Comment by bertfrees** [comment]
"textNCX" and "audioFullText" are both not supported. At the moment only "audioNCX" is supported.

**Comment by NandyJ** [comment]
Hi Bert,

Iam using DP2 windows version cli-2.1.7-windows_amd64.

Iam trying to convert html-to-pef with this command dp2.exe html-to-pef --source %i% --output %o% iam getting below error
<img width="959" alt="image" src="https://github.com/daisy/pipeline/assets/159104261/c37727cf-a1e8-4ac6-95fb-680bca5bb557">

Is anything i need to add in the script?

**Comment by bertfrees** [comment]
Hello. The command line interface works fine. This is an unrelated thing. The HTML to braille script needs the language to be indicated in the input document with a lang or xml:lang attribute, or otherwise the desired braille code must be specified using either the "braille-code" or "transform" option. See `dp2 help html-to-pef braille-code` and `dp2 help html-to-pef transform`.

**Comment by NandyJ** [comment]
Thank you bert,
I tried converting html-to-dtbook with the below command
dp2.exe html-to-dtbook "%i%" "%o%" iam getting error.
<img width="952" alt="image" src="https://github.com/daisy/pipeline/assets/159104261/7ee5543f-a1f8-4aaf-9124-b4d716b5e43a">
 What type of subcommand i need to provide for the conversion.

**Comment by NandyJ** [comment]
Hi Bert,

can you please help me on the above solution for html-to-dtbook conversion. Thank you.

**Comment by NandyJ** [comment]
Hi Bert,

Do DP2 pipeline has any command on rtf-to-pef and odt-to-pef conversion?

**Comment by bertfrees** [comment]
> I tried converting html-to-dtbook with the below command

Hmm indeed, HTML to DTBook is currently not in the list of scripts. I think we decided to not expose it for now because it is still too experimental.

> Do DP2 pipeline has any command on rtf-to-pef and odt-to-pef conversion?

No, we currently don't have any scripts that take an RTF or an ODT file. What comes closest is the Word to DTBook script that is available in the latest release (1.14.19). This can be used to convert a Word document to a DTBook. The resulting DTBook could then be converted to a PEF.

If you have more thinks you want to discuss with me, could you please open a [new issue](https://github.com/daisy/pipeline/issues/new/choose) or a [new discussion on the forum](https://github.com/daisy/pipeline/discussions/new/choose)? Thanks!
